// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function AddFile(arg1:string):Promise<boolean>;

export function AddFolder(arg1:string):Promise<string>;

export function CloseWindow(arg1:boolean):Promise<void>;

export function GetPostsContent(arg1:string):Promise<string>;

export function GetPostsList():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function KillPreview():Promise<void>;

export function MaximiseWindow():Promise<void>;

export function Menu():Promise<menu.Menu>;

export function OnTopWindow():Promise<void>;

export function OpenPreviewURL():Promise<void>;

export function ReStartPreview():Promise<void>;

export function RemoveFile(arg1:string):Promise<boolean>;

export function WindowIsOnToped():Promise<boolean>;

export function WritePostsContent(arg1:string,arg2:string):Promise<boolean>;
