// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function CloseWindow(arg1:boolean):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function MaximiseWindow():Promise<void>;

export function Menu():Promise<menu.Menu>;

export function OnTopWindow():Promise<void>;

export function WindowIsOnToped():Promise<boolean>;
