// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['backend']['App']['AddFile'](arg1);
}

export function AddFolder(arg1) {
  return window['go']['backend']['App']['AddFolder'](arg1);
}

export function CloseWindow(arg1) {
  return window['go']['backend']['App']['CloseWindow'](arg1);
}

export function GetPostsContent(arg1) {
  return window['go']['backend']['App']['GetPostsContent'](arg1);
}

export function GetPostsList() {
  return window['go']['backend']['App']['GetPostsList']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function KillPreview() {
  return window['go']['backend']['App']['KillPreview']();
}

export function MaximiseWindow() {
  return window['go']['backend']['App']['MaximiseWindow']();
}

export function Menu() {
  return window['go']['backend']['App']['Menu']();
}

export function OnTopWindow() {
  return window['go']['backend']['App']['OnTopWindow']();
}

export function OpenPreviewURL() {
  return window['go']['backend']['App']['OpenPreviewURL']();
}

export function ReStartPreview() {
  return window['go']['backend']['App']['ReStartPreview']();
}

export function RemoveFile(arg1) {
  return window['go']['backend']['App']['RemoveFile'](arg1);
}

export function WindowIsOnToped() {
  return window['go']['backend']['App']['WindowIsOnToped']();
}

export function WritePostsContent(arg1, arg2) {
  return window['go']['backend']['App']['WritePostsContent'](arg1, arg2);
}
