// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow(arg1) {
  return window['go']['backend']['App']['CloseWindow'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function Menu() {
  return window['go']['backend']['App']['Menu']();
}

export function OnTopWindow() {
  return window['go']['backend']['App']['OnTopWindow']();
}
